// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectPokemon.Models.Database;

#nullable disable

namespace ProjectPokemon.Migrations
{
    [DbContext(typeof(PokemonDbContext))]
    [Migration("20260128203732_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("ProjectPokemon.Models.Database.Entities.Movement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Accuracy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(100);

                    b.Property<bool>("Contact")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MovementClass")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Power")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Pp")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Movements");
                });

            modelBuilder.Entity("ProjectPokemon.Models.Database.Entities.Nature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StatBoost")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StatDrop")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Natures");
                });

            modelBuilder.Entity("ProjectPokemon.Models.Database.Entities.Pokemon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Attack")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cry")
                        .HasColumnType("TEXT");

                    b.Property<int>("Defense")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Hp")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SpecialAttack")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SpecialDefense")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Speed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SpriteBack")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SpriteBackFem")
                        .HasColumnType("TEXT");

                    b.Property<string>("SpriteBackFemShiny")
                        .HasColumnType("TEXT");

                    b.Property<string>("SpriteBackShiny")
                        .HasColumnType("TEXT");

                    b.Property<string>("SpriteFront")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SpriteFrontFem")
                        .HasColumnType("TEXT");

                    b.Property<string>("SpriteFrontFemShiny")
                        .HasColumnType("TEXT");

                    b.Property<string>("SpriteFrontShiny")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type1")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type2")
                        .HasColumnType("TEXT");

                    b.Property<int>("Weight")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Pokemons");
                });

            modelBuilder.Entity("ProjectPokemon.Models.Database.Entities.PokemonBattle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MovementId1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MovementId2")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MovementId3")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MovementId4")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NatureId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PokemonId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Shiny")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("None");

                    b.Property<int>("Team")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MovementId1");

                    b.HasIndex("MovementId2");

                    b.HasIndex("MovementId3");

                    b.HasIndex("MovementId4");

                    b.HasIndex("NatureId");

                    b.HasIndex("PokemonId");

                    b.ToTable("PokemonBattles");
                });

            modelBuilder.Entity("ProjectPokemon.Models.Database.Entities.PokemonMovement", b =>
                {
                    b.Property<int>("PokemonId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MovementId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PokemonId", "MovementId");

                    b.HasIndex("MovementId");

                    b.ToTable("PokemonMovements");
                });

            modelBuilder.Entity("ProjectPokemon.Models.Database.Entities.PokemonBattle", b =>
                {
                    b.HasOne("ProjectPokemon.Models.Database.Entities.Movement", "Movement1")
                        .WithMany()
                        .HasForeignKey("MovementId1")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProjectPokemon.Models.Database.Entities.Movement", "Movement2")
                        .WithMany()
                        .HasForeignKey("MovementId2")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProjectPokemon.Models.Database.Entities.Movement", "Movement3")
                        .WithMany()
                        .HasForeignKey("MovementId3")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProjectPokemon.Models.Database.Entities.Movement", "Movement4")
                        .WithMany()
                        .HasForeignKey("MovementId4")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProjectPokemon.Models.Database.Entities.Nature", "Nature")
                        .WithMany("PokemonBattles")
                        .HasForeignKey("NatureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProjectPokemon.Models.Database.Entities.Pokemon", "Pokemon")
                        .WithMany("PokemonBattles")
                        .HasForeignKey("PokemonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Movement1");

                    b.Navigation("Movement2");

                    b.Navigation("Movement3");

                    b.Navigation("Movement4");

                    b.Navigation("Nature");

                    b.Navigation("Pokemon");
                });

            modelBuilder.Entity("ProjectPokemon.Models.Database.Entities.PokemonMovement", b =>
                {
                    b.HasOne("ProjectPokemon.Models.Database.Entities.Movement", "Movement")
                        .WithMany("PokemonMovements")
                        .HasForeignKey("MovementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectPokemon.Models.Database.Entities.Pokemon", "Pokemon")
                        .WithMany("PokemonMovements")
                        .HasForeignKey("PokemonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movement");

                    b.Navigation("Pokemon");
                });

            modelBuilder.Entity("ProjectPokemon.Models.Database.Entities.Movement", b =>
                {
                    b.Navigation("PokemonMovements");
                });

            modelBuilder.Entity("ProjectPokemon.Models.Database.Entities.Nature", b =>
                {
                    b.Navigation("PokemonBattles");
                });

            modelBuilder.Entity("ProjectPokemon.Models.Database.Entities.Pokemon", b =>
                {
                    b.Navigation("PokemonBattles");

                    b.Navigation("PokemonMovements");
                });
#pragma warning restore 612, 618
        }
    }
}
